Reducers actions
RoyJumah/React-Bookstore pull request #3
Opened 2023-01-23 20:09 UTC by RoyJumah

> In this pull request I was able to complete the following tasks;

-  [x]  Implement the functionalities of deleting and adding a book in the UI
-  [x]  Used the duck's pattern to write reducers and actions for deleting and adding a book
 - [x]  Created reducers and actions for the categories section
 - [x]  Combined both the reducers in the configuration function

2023-01-23 20:45 UTC, prolajumokeoni commented
Hi @RoyJumah, kindly add the future features section to your readme

2023-01-23 20:58 UTC, RoyJumah commented
> Hi @RoyJumah, kindly add the future features section to your readme

@prolajumokeoni Done

2023-01-23 21:04 UTC, prolajumokeoni requested changes
Hi @RoyJumah 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used 
✔️  Good PR title and Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 21:04 UTC, prolajumokeoni commented on src/redux/books/Books.js
> +export const REMOVE_BOOK = 'books/REMOVE_BOOK';
- [ ] The value of each action type needs to follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux), so it will be something like:       const ADD_BOOK = React-Bookstore/books/ADD_BOOK and const REMOVE_BOOK = React-Bookstore/books/REMOVE_BOOK

2023-01-23 21:04 UTC, prolajumokeoni commented on src/redux/categories/categories.js
> +export const CHECK_STATUS = 'categories/CHECK_STATUS';
- [ ] The value of action type needs to follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux), so it will be something like: `const CHECK_STATUS = React-Bookstore/categories/CHECK_STATUS`

2023-01-24 03:55 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @RoyJumah 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 03:55 UTC, tresorsawasawa commented on src/redux/books/Books.js
> +
- [ ] As mentioned by the previous reviewer the value of each action type  to follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux), I think you should update each one the correct result by correcting the typo_erros. 
```JavaScript
// Bad
export const ADD_BOOK = 'bookStore/Book/ADD_BOOK ';
export const REMOVE_BOOK = 'bookStore/Book/REMOVE_BOOK';

// Good
const ADD_BOOK = React-Bookstore/books/ADD_BOOK;
const REMOVE_BOOK = React-Bookstore/books/REMOVE_BOOK;
```

- [ **OPTIONAL** ] I  think it would be better if you change the `src/redux/books/Books.js` module name to `src/redux/books/books.js`, so this will follow the correct structure of naming.

2023-01-24 03:55 UTC, tresorsawasawa commented on src/redux/categories/categories.js
> +export const SET_CATEGORIES = 'bookStore/categories/SET_CATEGORIES';
- [ ] As I mentioned in the previous comment, I suggest you correct your typing errors, so the value of each action type  to follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux). i.e.:
```JavaScript
// Bad
 const CHECK_STATUS = 'bookStore/categories/CHECK_STATUS';
 const SET_CATEGORIES = 'bookStore/categories/SET_CATEGORIES';

// Good
 const CHECK_STATUS = 'React-Bookstore/categories/CHECK_STATUS';
 const SET_CATEGORIES = 'React-Bookstore/categories/SET_CATEGORIES';
```

2023-01-24 04:10 UTC, RoyJumah commented on src/redux/books/Books.js
> +
@tresorsawasawa Is this the way it should be?

```
export const ADD_BOOK = "React-Bookstore/categories/CHECK_STATUS";
export const REMOVE_BOOK = "React-Bookstore/books/REMOVE_BOOK";

```

2023-01-24 04:14 UTC, tresorsawasawa commented on src/redux/books/Books.js
> +
Hi @RoyJumah 
For books:
```
const ADD_BOOK = 'React-Bookstore/books/ADD_BOOK';
const REMOVE_BOOK = 'React-Bookstore/books/REMOVE_BOOK';
```

2023-01-24 04:16 UTC, RoyJumah commented on src/redux/books/Books.js
> +
Thanks

2023-01-24 04:36 UTC, Reem-lab approved these changes
# Hi @RoyJumah, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>

## Highlights
- No Linters error ✅
- Followed Gitflow ✅
- Great working on the functionlaity ✅
- Descriptive PR ✅
- Professional README ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 04:38 UTC, merged